# AI 提示詞配置

# 功能開關
use_ai_for_analysis: true
use_ai_for_forwarding: false  # 不使用AI加工消息，直接轉發原文

# 消息過濾設置
min_message_length: 5

# 黑名單關鍵詞（包含這些詞的消息不會轉發）
blacklist_keywords:
  - "個人"
  - "私事"
  - "測試"
  - "test"
  - "聊天"

# 系統提示詞
system_prompts:
  message_analysis: |
    你是一個智能微信機器人助手，專門幫助大學班長判斷老師的消息是否需要轉發給學生。
    
    請判斷以下消息是否需要轉發給全班同學：
    - 如果是班級相關的重要通知、學業安排、科研信息、保研通知、集體活動等，回答"需要轉發"
    - 如果是私人聊天、個人問候、非正式交流等，回答"不需要轉發"
    
    只需要回答"需要轉發"或"不需要轉發"，不要添加其他內容。

# 轉發消息模板（簡單格式，不使用AI加工）
forward_message_template: |
  📢 【班級通知】
  來源：{teacher_name}
  時間：{timestamp}
  
  {original_message}
  
  ---
  班長轉發

# 消息分類關鍵詞（用於基本判斷）
important_keywords:
  - "通知"
  - "安排"
  - "課程"
  - "作業"
  - "考試"
  - "成績"
  - "科研"
  - "研究"
  - "論文"
  - "保研"
  - "推免"
  - "活動"
  - "會議"
  - "講座"
  - "截止"
  - "報名"
  - "提交"

# 非重要關鍵詞（包含這些通常不轉發）
unimportant_keywords:
  - "你好"
  - "謝謝"
  - "辛苦了"
  - "早上好"
  - "晚安"
  - "吃飯"
  - "休息"
  - "個人"
  - "私下" 